### ISSUE TITLE
Bitski Sidechain Support Fix

### ISSUE THREAD

**Issue by christinerenee** [BitskiCo/bitski-js#133]
**Describe the bug**
When attemping to connect Bitski to a SKALE elastic sidechain, I receive a CORS error due to request headers that should not be sent to SKALE. 

<img width="1121" alt="CORS-Bitski" src="https://user-images.githubusercontent.com/3582136/58903188-a2358900-86b9-11e9-87f7-71a0d4911269.png">

**To Reproduce**
1. Connect Bitski to SKALE
```
const bitski = new Bitski('<YOUR-CLIENT-ID>', '<YOUR-REDIRECT-URL>');
const network = {
  rpcUrl: '<YOUR-SKALE-ENDPOINT>',
  chainId: 1
}
const provider = bitski.getProvider({ network });
let web3 = new Web3(provider);
```

**Expected behavior**
A potential fix will be to remove the headers when sending requests to networks that contain a `rpcUrl` within the `bitski-browser-engine` at line 41.

[bitski-browser-engine.ts (line 41)](https://github.com/BitskiCo/bitski-js/blob/c146e17721140b2b99e316d4769ae5cbc8357cf3/packages/browser/src/providers/bitski-browser-engine.ts#L41)

***Change***
```
const defaultHeaders = {
    'X-API-KEY': this.clientId,
    'X-CLIENT-ID': this.clientId,
    'X-CLIENT-VERSION': this.sdkVersion,
};
```

***To***
```
const defaultHeaders = {};
if("rpcUrl" in network === false) {
    defaultHeaders = {
        'X-API-KEY': this.clientId,
        'X-CLIENT-ID': this.clientId,
        'X-CLIENT-VERSION': this.sdkVersion,
    };
}
```

**Desktop:**
 - OS: Mac
 - Browser Chrome
 - Version 74.0.3729.169

**SDK:**
- Version Bitski-js 6.0 & 0.7.0-alpha.0

**Additional context**
I work at SKALE Labs, and am working on verifying support between SKALE and API based wallets. I really love what you are building at Bitski, and I look forward to following the progress!

**Comment by pixelmatrix** [comment]
Hey @christinerenee - thanks for letting us know! That header certainly isn't necessary for non-bitski endpoints, so we'll remove it from the requests. Should have an update in the next couple days :)

**Comment by christinerenee** [comment]
Thanks @pixelmatrix!

**Comment by pixelmatrix** [comment]
@christinerenee Just released 0.6.1 with a fix. Can you update and let us know if it's working for you now?

**Comment by christinerenee** [comment]
Thanks @pixelmatrix! The fix works!

**Comment by pixelmatrix** [comment]
So glad to hear that! Please let us know if you have any other feedback using Bitski on another chain. We are excited about the possibilities there :)
