### ISSUE TITLE
0.15.0 gives dependency errors.

### ISSUE THREAD

**Issue by tawago** [BitskiCo/bitski-js#238]
**Describe the bug**
`Module not found: Error: Can't resolve '@bitski/provider-engine' in '***/node_modules/bitski-provider/dist'`
`Module not found: Error: Can't resolve 'promise-to-callback' in '***/node_modules/bitski/dist/esm/subproviders'`
`Module not found: Error: Can't resolve 'cross-fetch' in '***/node_modules/bitski/dist/esm/subproviders'`

**To Reproduce**

1. `yarn add bitski@0.14.1`
2. `yarn serve` or equivalent to start your app
3.  make sure there is no errors
4. `yarn add bitski@0.15.0`
5. `yarn serve` or equivalent to start your app
6. See error

or to be more cautious 
7. `rm -r node_module && rm yarn-lock`
8. `yarn install`
9. `yarn serve` or equivalent to start your app
10. See error

**Expected behavior**
`bitski@0.14.1` does not give any of these dependency errors

**Desktop (please complete the following information):**
- OS: [Mac Catalina 10.15.7]
- Browser [chrome]
- Version [Version 102.0.5005.115]

**Additional context**
This seems to be introduced in https://github.com/BitskiCo/bitski-js/pull/229

I have NOT cloned the repo and installed `lerna`, assuming installing libraries from npm should not require users to go through such extra steps .

**Comment by imthinhvu** [comment]
@tawago - this is a known issue and we have resolved it in the latest package version. Please upgrade to `0.16.0` or `0.16.1` - we apologize for the inconvenience you faced with this!
